### PR TITLE
modified Header, License, created mobile menu, modified Chat, Manage Users, Manage Domains and Manage Roles

### PR DESCRIPTION
**Pull request by Makuzaza**
- Modified header: Added hover effects
- Mobile page: Added Language and Logout/Login buttons for the mobile version of the site.
- Active links: Underlined active links to clearly indicate the current page or section.
Header

- Mobile menu: Created a mobile menu for screens smaller than 1000px, positioned on the left side.
mobile_menu

- License button: Adjusted the display of the License button to be on the right side.
- License section: Moved the License section to the right side for better alignment.
License

- Manage users: Redesigned the Manage Users section with a responsive table that displays in a traditional table format on desktops and a column format on mobile devices, text alignment
manage_users

- Adjusted the verified Login window to fit the screen without exceeding its bounds in main screen
main

- Updated input fields in the My Profile section to be responsive
- Added a textarea in the Chat section to ensure text visibility while typing
chat
chat1

- Completely modified the Manage Users section for a better mobile experience. The dropdown menu functionality has been fixed to ensure it operates correctly for individual users
users
add

- Improved mobile views for the Add Modal, Change Password, Change Roles, Deactivate, and Verify User sections.
domain
role

- Improved the Manage Domains and Manage Roles sections by adding a column layout, a Back buttons for the Edit section, and modifying the Add role section for better usability.
back
domain1

### CODE REVIEW

**Comment by foghorn-hash** [comment]
Good job! Thanks.

**Comment by foghorn-hash** [comment]
But there is not enough changes to done for purpose to merge any Source Code changes to main branch.

**Comment by foghorn-hash** [comment]
And also permission is user logged-in or not check and permission checks is some user role rights to to see menu items missing.

**Comment by Makuzaza** [comment]
> And also permission is user logged-in or not check and permission checks is some user role rights to to see menu items missing.

ok, I'am working on it

**Comment by foghorn-hash** [comment]
Hello, good job. I will merge your changes now to production. Thanks.

**Pull request merged**
